### ISSUE TITLE
namespace stuttering

### ISSUE THREAD

**Issue by danieleades** [JoelCourtney/mdbook-kroki-preprocessor#11]
this preprocessor is called 'kroki-preprocessor', which is kind of redundant.
It's a breaking change, but it would be nice to configure this as

```toml
[book]
authors = ["You"]
language = "en"
multilingual = false
src = "src"
title = "example"

[preprocessor.kroki]
```

instead of

```toml
[book]
authors = ["You"]
language = "en"
multilingual = false
src = "src"
title = "example"

[preprocessor.kroki-preprocessor]
```
